language: python
python:
    - "2.7"
    - "3.3"
install:
    - if [ "${PYTHON}" == "3.4" ]; then
          pip3 install PyMySQL;
      else
          pip install MySQL-python
      fi;
script:
    - python setup.py test